package com.xscroll.debug

import androidx.compose.ui.graphics.Color
import com.google.firebase.Timestamp
import com.xscroll.data.model.DanmakuMessage
import com.xscroll.data.model.Video

object FakeVideos {

    val videoColors = mapOf(
        "fake_001" to Color(0xFF1A1A2E),
        "fake_002" to Color(0xFF1B1B0A),
        "fake_003" to Color(0xFF1A0A0A),
        "fake_004" to Color(0xFF0A1A1A),
        "fake_005" to Color(0xFF120A1A),
        "fake_006" to Color(0xFF1A1A0A),
        "fake_007" to Color(0xFF0A0A1A),
        "fake_008" to Color(0xFF1A0A1A),
        "fake_009" to Color(0xFF0A1A0A),
        "fake_010" to Color(0xFF1A1A1A),
        "fake_011" to Color(0xFF0F1A2E),
        "fake_012" to Color(0xFF1A0F0A),
    )

    val videos = listOf(
        Video(id = "fake_001", storageUrl = "https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4", uploadedBy = "debug_user", createdAt = Timestamp.now()),
        Video(id = "fake_002", storageUrl = "https://test-videos.co.uk/vids/jellyfish/mp4/h264/360/Jellyfish_360_10s_1MB.mp4", uploadedBy = "debug_user", createdAt = Timestamp.now()),
        Video(id = "fake_003", storageUrl = "https://test-videos.co.uk/vids/sintel/mp4/h264/360/Sintel_360_10s_1MB.mp4", uploadedBy = "debug_user", createdAt = Timestamp.now()),
        Video(id = "fake_004", storageUrl = "https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_2MB.mp4", uploadedBy = "debug_user", createdAt = Timestamp.now()),
        Video(id = "fake_005", storageUrl = "https://test-videos.co.uk/vids/jellyfish/mp4/h264/360/Jellyfish_360_10s_2MB.mp4", uploadedBy = "debug_user", createdAt = Timestamp.now()),
        Video(id = "fake_006", storageUrl = "https://test-videos.co.uk/vids/sintel/mp4/h264/360/Sintel_360_10s_2MB.mp4", uploadedBy = "debug_user", createdAt = Timestamp.now()),
        Video(id = "fake_007", storageUrl = "https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/480/Big_Buck_Bunny_480_10s_1MB.mp4", uploadedBy = "debug_user", createdAt = Timestamp.now()),
        Video(id = "fake_008", storageUrl = "https://test-videos.co.uk/vids/jellyfish/mp4/h264/480/Jellyfish_480_10s_1MB.mp4", uploadedBy = "debug_user", createdAt = Timestamp.now()),
        Video(id = "fake_009", storageUrl = "https://test-videos.co.uk/vids/sintel/mp4/h264/480/Sintel_480_10s_1MB.mp4", uploadedBy = "debug_user", createdAt = Timestamp.now()),
        Video(id = "fake_010", storageUrl = "https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/480/Big_Buck_Bunny_480_10s_2MB.mp4", uploadedBy = "debug_user", createdAt = Timestamp.now()),
        Video(id = "fake_011", storageUrl = "https://test-videos.co.uk/vids/jellyfish/mp4/h264/480/Jellyfish_480_10s_2MB.mp4", uploadedBy = "debug_user", createdAt = Timestamp.now()),
        Video(id = "fake_012", storageUrl = "https://test-videos.co.uk/vids/sintel/mp4/h264/480/Sintel_480_10s_2MB.mp4", uploadedBy = "debug_user", createdAt = Timestamp.now()),
    )

    // timestampMs: loop 0 = 0–2999, loop 1 = 3000–5999, loop 2 = 6000–8999
    val danmakuByVideo = mapOf(
        "fake_001" to listOf(
            // Loop 0
            DanmakuMessage(id = "1_01", text = "bro what is this", color = "#FFFFFF", timestampMs = 100),
            DanmakuMessage(id = "1_02", text = "W", color = "#FFD700", timestampMs = 300),
            DanmakuMessage(id = "1_03", text = "fire content ngl", color = "#FFFFFF", timestampMs = 550),
            DanmakuMessage(id = "1_04", text = "bunny goes crazy", color = "#FF69B4", timestampMs = 800),
            DanmakuMessage(id = "1_05", text = "this is peak cinema", color = "#00FF88", timestampMs = 1050),
            DanmakuMessage(id = "1_06", text = "no way lmaooo", color = "#FFFFFF", timestampMs = 1300),
            DanmakuMessage(id = "1_07", text = "someone clip this", color = "#FFD700", timestampMs = 1600),
            DanmakuMessage(id = "1_08", text = "the ears tho", color = "#00BFFF", timestampMs = 1900),
            DanmakuMessage(id = "1_09", text = "fluffy king", color = "#FF6B6B", timestampMs = 2200),
            DanmakuMessage(id = "1_10", text = "caught in 4k", color = "#FFFFFF", timestampMs = 2500),
            DanmakuMessage(id = "1_11", text = "nature documentary fr", color = "#00FF88", timestampMs = 2800),
            // Loop 1
            DanmakuMessage(id = "1_12", text = "im dead", color = "#FF6B6B", timestampMs = 3100),
            DanmakuMessage(id = "1_13", text = "W post W post", color = "#FFFFFF", timestampMs = 3350),
            DanmakuMessage(id = "1_14", text = "goated fr fr", color = "#00BFFF", timestampMs = 3600),
            DanmakuMessage(id = "1_15", text = "how is this free", color = "#FFD700", timestampMs = 3900),
            DanmakuMessage(id = "1_16", text = "the bunny has rizz", color = "#FF69B4", timestampMs = 4200),
            DanmakuMessage(id = "1_17", text = "lol what", color = "#FFFFFF", timestampMs = 4500),
            DanmakuMessage(id = "1_18", text = "absolute unit", color = "#00FF88", timestampMs = 4800),
            DanmakuMessage(id = "1_19", text = "built different", color = "#FFD700", timestampMs = 5100),
            DanmakuMessage(id = "1_20", text = "main character energy", color = "#FF6B6B", timestampMs = 5400),
            DanmakuMessage(id = "1_21", text = "plot twist incoming", color = "#00BFFF", timestampMs = 5700),
            // Loop 2
            DanmakuMessage(id = "1_22", text = "still watching", color = "#00FF88", timestampMs = 6100),
            DanmakuMessage(id = "1_23", text = "third loop and still fire", color = "#FFD700", timestampMs = 6350),
            DanmakuMessage(id = "1_24", text = "cant stop replaying", color = "#FF6B6B", timestampMs = 6600),
            DanmakuMessage(id = "1_25", text = "addicted to this", color = "#FFFFFF", timestampMs = 6900),
            DanmakuMessage(id = "1_26", text = "best video on here", color = "#00BFFF", timestampMs = 7200),
            DanmakuMessage(id = "1_27", text = "take all my tokens", color = "#FFD700", timestampMs = 7500),
            DanmakuMessage(id = "1_28", text = "dopamine overload", color = "#FF69B4", timestampMs = 7800),
            DanmakuMessage(id = "1_29", text = "bunny AOTY", color = "#FFFFFF", timestampMs = 8100),
            DanmakuMessage(id = "1_30", text = "see yall next loop", color = "#00FF88", timestampMs = 8500),
        ),
        "fake_002" to listOf(
            // Loop 0
            DanmakuMessage(id = "2_01", text = "okay this one goes hard", color = "#FFFFFF", timestampMs = 100),
            DanmakuMessage(id = "2_02", text = "literally me at 3am", color = "#FF69B4", timestampMs = 350),
            DanmakuMessage(id = "2_03", text = "jellyfish arc", color = "#00BFFF", timestampMs = 600),
            DanmakuMessage(id = "2_04", text = "so peaceful ngl", color = "#FFFFFF", timestampMs = 850),
            DanmakuMessage(id = "2_05", text = "vibes", color = "#FFD700", timestampMs = 1100),
            DanmakuMessage(id = "2_06", text = "nature is healing", color = "#00FF88", timestampMs = 1400),
            DanmakuMessage(id = "2_07", text = "the ocean called", color = "#00BFFF", timestampMs = 1700),
            DanmakuMessage(id = "2_08", text = "blob of perfection", color = "#FF6B6B", timestampMs = 2000),
            DanmakuMessage(id = "2_09", text = "majestic", color = "#FFD700", timestampMs = 2300),
            DanmakuMessage(id = "2_10", text = "float on king", color = "#FFFFFF", timestampMs = 2600),
            DanmakuMessage(id = "2_11", text = "zero stress rn", color = "#FF69B4", timestampMs = 2900),
            // Loop 1
            DanmakuMessage(id = "2_12", text = "i could watch this forever", color = "#FFFFFF", timestampMs = 3100),
            DanmakuMessage(id = "2_13", text = "ocean gang rise up", color = "#00BFFF", timestampMs = 3400),
            DanmakuMessage(id = "2_14", text = "W jellyfish", color = "#FFD700", timestampMs = 3700),
            DanmakuMessage(id = "2_15", text = "this cured my anxiety", color = "#FF69B4", timestampMs = 3950),
            DanmakuMessage(id = "2_16", text = "therapy is expensive this is free", color = "#FFFFFF", timestampMs = 4200),
            DanmakuMessage(id = "2_17", text = "squishy boi", color = "#00FF88", timestampMs = 4500),
            DanmakuMessage(id = "2_18", text = "translucent goals", color = "#00BFFF", timestampMs = 4800),
            DanmakuMessage(id = "2_19", text = "no bones no problems", color = "#FFD700", timestampMs = 5100),
            DanmakuMessage(id = "2_20", text = "invertebrate supremacy", color = "#FF6B6B", timestampMs = 5400),
            DanmakuMessage(id = "2_21", text = "living the dream", color = "#FFFFFF", timestampMs = 5700),
            // Loop 2
            DanmakuMessage(id = "2_22", text = "3rd loop no skip", color = "#FFD700", timestampMs = 6100),
            DanmakuMessage(id = "2_23", text = "the way it moves", color = "#FF69B4", timestampMs = 6400),
            DanmakuMessage(id = "2_24", text = "nature documentary fr", color = "#FFFFFF", timestampMs = 6700),
            DanmakuMessage(id = "2_25", text = "serotonin", color = "#00BFFF", timestampMs = 6950),
            DanmakuMessage(id = "2_26", text = "peace and love", color = "#FFD700", timestampMs = 7200),
            DanmakuMessage(id = "2_27", text = "protect the oceans", color = "#00FF88", timestampMs = 7500),
            DanmakuMessage(id = "2_28", text = "save the jelly", color = "#FF6B6B", timestampMs = 7800),
            DanmakuMessage(id = "2_29", text = "we dont deserve this", color = "#FFFFFF", timestampMs = 8100),
            DanmakuMessage(id = "2_30", text = "aight imma stay", color = "#FFD700", timestampMs = 8500),
        ),
        "fake_003" to listOf(
            // Loop 0
            DanmakuMessage(id = "3_01", text = "wait WHAT", color = "#FFFFFF", timestampMs = 100),
            DanmakuMessage(id = "3_02", text = "how did u do that", color = "#FFD700", timestampMs = 350),
            DanmakuMessage(id = "3_03", text = "sintel supremacy", color = "#FF6B6B", timestampMs = 600),
            DanmakuMessage(id = "3_04", text = "the animation tho", color = "#FFFFFF", timestampMs = 900),
            DanmakuMessage(id = "3_05", text = "better than disney", color = "#00FF88", timestampMs = 1200),
            DanmakuMessage(id = "3_06", text = "open source king", color = "#FFD700", timestampMs = 1500),
            DanmakuMessage(id = "3_07", text = "shader game crazy", color = "#00BFFF", timestampMs = 1800),
            DanmakuMessage(id = "3_08", text = "who made this", color = "#FF69B4", timestampMs = 2100),
            DanmakuMessage(id = "3_09", text = "CGI is unmatched", color = "#FFFFFF", timestampMs = 2400),
            DanmakuMessage(id = "3_10", text = "actually insane", color = "#FF6B6B", timestampMs = 2700),
            // Loop 1
            DanmakuMessage(id = "3_11", text = "blender gang", color = "#00BFFF", timestampMs = 3100),
            DanmakuMessage(id = "3_12", text = "this goes so hard", color = "#FFFFFF", timestampMs = 3400),
            DanmakuMessage(id = "3_13", text = "rent free in my head", color = "#FF69B4", timestampMs = 3700),
            DanmakuMessage(id = "3_14", text = "cinema", color = "#FFD700", timestampMs = 3950),
            DanmakuMessage(id = "3_15", text = "the lighting is insane", color = "#FFFFFF", timestampMs = 4200),
            DanmakuMessage(id = "3_16", text = "volumetric clouds??", color = "#00FF88", timestampMs = 4500),
            DanmakuMessage(id = "3_17", text = "ray tracing vibes", color = "#00BFFF", timestampMs = 4800),
            DanmakuMessage(id = "3_18", text = "the hair physics", color = "#FFD700", timestampMs = 5100),
            DanmakuMessage(id = "3_19", text = "every frame a painting", color = "#FF6B6B", timestampMs = 5400),
            DanmakuMessage(id = "3_20", text = "screenshot worthy", color = "#FFFFFF", timestampMs = 5700),
            // Loop 2
            DanmakuMessage(id = "3_21", text = "goosebumps every time", color = "#FF6B6B", timestampMs = 6100),
            DanmakuMessage(id = "3_22", text = "actual art", color = "#FFD700", timestampMs = 6400),
            DanmakuMessage(id = "3_23", text = "masterpiece", color = "#00FF88", timestampMs = 6700),
            DanmakuMessage(id = "3_24", text = "chills literal chills", color = "#FFFFFF", timestampMs = 7000),
            DanmakuMessage(id = "3_25", text = "need the full movie", color = "#00BFFF", timestampMs = 7300),
            DanmakuMessage(id = "3_26", text = "petition signed", color = "#FF69B4", timestampMs = 7600),
            DanmakuMessage(id = "3_27", text = "would crowdfund this", color = "#FFD700", timestampMs = 7900),
            DanmakuMessage(id = "3_28", text = "emotional rn", color = "#FF6B6B", timestampMs = 8200),
            DanmakuMessage(id = "3_29", text = "pure art", color = "#FFFFFF", timestampMs = 8500),
            DanmakuMessage(id = "3_30", text = "bravo bravo bravo", color = "#00FF88", timestampMs = 8800),
        ),
        "fake_004" to listOf(
            // Loop 0
            DanmakuMessage(id = "4_01", text = "okay I see you", color = "#FFFFFF", timestampMs = 100),
            DanmakuMessage(id = "4_02", text = "underrated asf", color = "#FF69B4", timestampMs = 350),
            DanmakuMessage(id = "4_03", text = "big bunny energy", color = "#FFD700", timestampMs = 600),
            DanmakuMessage(id = "4_04", text = "round 2 lets gooo", color = "#00FF88", timestampMs = 900),
            DanmakuMessage(id = "4_05", text = "still goes hard", color = "#FFFFFF", timestampMs = 1150),
            DanmakuMessage(id = "4_06", text = "the sequel we needed", color = "#00BFFF", timestampMs = 1400),
            DanmakuMessage(id = "4_07", text = "plot thickens", color = "#FF6B6B", timestampMs = 1700),
            DanmakuMessage(id = "4_08", text = "lore drop", color = "#FFD700", timestampMs = 2000),
            DanmakuMessage(id = "4_09", text = "bunny extended universe", color = "#FFFFFF", timestampMs = 2300),
            DanmakuMessage(id = "4_10", text = "bigger budget fr", color = "#FF69B4", timestampMs = 2600),
            // Loop 1
            DanmakuMessage(id = "4_11", text = "HQ version hits different", color = "#FFD700", timestampMs = 3100),
            DanmakuMessage(id = "4_12", text = "absolutely goated", color = "#FF6B6B", timestampMs = 3400),
            DanmakuMessage(id = "4_13", text = "the detail in this", color = "#FFFFFF", timestampMs = 3700),
            DanmakuMessage(id = "4_14", text = "chef kiss", color = "#FF69B4", timestampMs = 3950),
            DanmakuMessage(id = "4_15", text = "grass rendering on point", color = "#00FF88", timestampMs = 4200),
            DanmakuMessage(id = "4_16", text = "butterfly spotted", color = "#FFD700", timestampMs = 4500),
            DanmakuMessage(id = "4_17", text = "the wind animation", color = "#00BFFF", timestampMs = 4800),
            DanmakuMessage(id = "4_18", text = "immersive", color = "#FFFFFF", timestampMs = 5100),
            DanmakuMessage(id = "4_19", text = "feels like a game cutscene", color = "#FF6B6B", timestampMs = 5400),
            DanmakuMessage(id = "4_20", text = "unreal engine who", color = "#FFD700", timestampMs = 5700),
            // Loop 2
            DanmakuMessage(id = "4_21", text = "why is this so good", color = "#FFD700", timestampMs = 6100),
            DanmakuMessage(id = "4_22", text = "bunny supremacy", color = "#00FF88", timestampMs = 6400),
            DanmakuMessage(id = "4_23", text = "loop 3 gang", color = "#FFFFFF", timestampMs = 6700),
            DanmakuMessage(id = "4_24", text = "never leaving", color = "#00BFFF", timestampMs = 6950),
            DanmakuMessage(id = "4_25", text = "subscribed forever", color = "#FFD700", timestampMs = 7200),
            DanmakuMessage(id = "4_26", text = "where is part 3", color = "#FF69B4", timestampMs = 7500),
            DanmakuMessage(id = "4_27", text = "trilogy when", color = "#FF6B6B", timestampMs = 7800),
            DanmakuMessage(id = "4_28", text = "would watch a 2hr cut", color = "#FFFFFF", timestampMs = 8100),
            DanmakuMessage(id = "4_29", text = "big bunny forever", color = "#00FF88", timestampMs = 8400),
            DanmakuMessage(id = "4_30", text = "goat tier", color = "#FFD700", timestampMs = 8700),
        ),
        "fake_005" to listOf(
            // Loop 0
            DanmakuMessage(id = "5_01", text = "this is the one", color = "#FFFFFF", timestampMs = 150),
            DanmakuMessage(id = "5_02", text = "legendary post", color = "#FFD700", timestampMs = 400),
            DanmakuMessage(id = "5_03", text = "jelly szn", color = "#00BFFF", timestampMs = 650),
            DanmakuMessage(id = "5_04", text = "so satisfying to watch", color = "#FFFFFF", timestampMs = 950),
            DanmakuMessage(id = "5_05", text = "mesmerizing fr", color = "#FF69B4", timestampMs = 1200),
            DanmakuMessage(id = "5_06", text = "the glow up", color = "#FFD700", timestampMs = 1500),
            DanmakuMessage(id = "5_07", text = "transparent king", color = "#00FF88", timestampMs = 1800),
            DanmakuMessage(id = "5_08", text = "pulsing with energy", color = "#FF6B6B", timestampMs = 2100),
            DanmakuMessage(id = "5_09", text = "alien vibes", color = "#00BFFF", timestampMs = 2400),
            DanmakuMessage(id = "5_10", text = "ocean is wild", color = "#FFFFFF", timestampMs = 2700),
            // Loop 1
            DanmakuMessage(id = "5_11", text = "4K jellyfish when", color = "#00FF88", timestampMs = 3050),
            DanmakuMessage(id = "5_12", text = "W content creator", color = "#FFFFFF", timestampMs = 3300),
            DanmakuMessage(id = "5_13", text = "take my tokens", color = "#FFD700", timestampMs = 3600),
            DanmakuMessage(id = "5_14", text = "need more of this", color = "#FF6B6B", timestampMs = 3900),
            DanmakuMessage(id = "5_15", text = "the tentacles are hypnotic", color = "#00BFFF", timestampMs = 4150),
            DanmakuMessage(id = "5_16", text = "deep sea ASMR", color = "#FF69B4", timestampMs = 4400),
            DanmakuMessage(id = "5_17", text = "put this in a museum", color = "#FFD700", timestampMs = 4700),
            DanmakuMessage(id = "5_18", text = "bioluminescence check", color = "#00FF88", timestampMs = 5000),
            DanmakuMessage(id = "5_19", text = "glowing up literally", color = "#FFFFFF", timestampMs = 5300),
            DanmakuMessage(id = "5_20", text = "sea creature of the year", color = "#00BFFF", timestampMs = 5600),
            DanmakuMessage(id = "5_21", text = "no predators just vibes", color = "#FF6B6B", timestampMs = 5900),
            // Loop 2
            DanmakuMessage(id = "5_22", text = "still here", color = "#FFFFFF", timestampMs = 6100),
            DanmakuMessage(id = "5_23", text = "this never gets old", color = "#FF69B4", timestampMs = 6400),
            DanmakuMessage(id = "5_24", text = "aquarium vibes", color = "#00FF88", timestampMs = 6700),
            DanmakuMessage(id = "5_25", text = "just keep swimming", color = "#FFD700", timestampMs = 6950),
            DanmakuMessage(id = "5_26", text = "calming asf", color = "#00BFFF", timestampMs = 7200),
            DanmakuMessage(id = "5_27", text = "inject into my veins", color = "#FF6B6B", timestampMs = 7500),
            DanmakuMessage(id = "5_28", text = "screensaver material", color = "#FFFFFF", timestampMs = 7800),
            DanmakuMessage(id = "5_29", text = "living wallpaper", color = "#FFD700", timestampMs = 8100),
            DanmakuMessage(id = "5_30", text = "perfection exists", color = "#00FF88", timestampMs = 8500),
        ),
        "fake_006" to listOf(
            // Loop 0
            DanmakuMessage(id = "6_01", text = "yooo sintel again", color = "#FFFFFF", timestampMs = 100),
            DanmakuMessage(id = "6_02", text = "never gets old", color = "#FFD700", timestampMs = 350),
            DanmakuMessage(id = "6_03", text = "the lighting is insane", color = "#00BFFF", timestampMs = 600),
            DanmakuMessage(id = "6_04", text = "actual art", color = "#FF69B4", timestampMs = 900),
            DanmakuMessage(id = "6_05", text = "free software did this", color = "#00FF88", timestampMs = 1200),
            DanmakuMessage(id = "6_06", text = "render farm goes brrr", color = "#FF6B6B", timestampMs = 1500),
            DanmakuMessage(id = "6_07", text = "the dragon design tho", color = "#FFD700", timestampMs = 1800),
            DanmakuMessage(id = "6_08", text = "scales look real", color = "#FFFFFF", timestampMs = 2100),
            DanmakuMessage(id = "6_09", text = "particle effects insane", color = "#00BFFF", timestampMs = 2400),
            DanmakuMessage(id = "6_10", text = "epic fantasy vibes", color = "#FF69B4", timestampMs = 2700),
            // Loop 1
            DanmakuMessage(id = "6_11", text = "goosebumps every time", color = "#FFFFFF", timestampMs = 3100),
            DanmakuMessage(id = "6_12", text = "masterpiece", color = "#FFD700", timestampMs = 3400),
            DanmakuMessage(id = "6_13", text = "chills", color = "#FF6B6B", timestampMs = 3700),
            DanmakuMessage(id = "6_14", text = "blender is the GOAT", color = "#00BFFF", timestampMs = 3950),
            DanmakuMessage(id = "6_15", text = "emotional damage", color = "#FFFFFF", timestampMs = 4200),
            DanmakuMessage(id = "6_16", text = "the score tho", color = "#FFD700", timestampMs = 4500),
            DanmakuMessage(id = "6_17", text = "hans zimmer vibes", color = "#FF69B4", timestampMs = 4800),
            DanmakuMessage(id = "6_18", text = "epic orchestra moment", color = "#00FF88", timestampMs = 5100),
            DanmakuMessage(id = "6_19", text = "goated soundtrack", color = "#FF6B6B", timestampMs = 5400),
            DanmakuMessage(id = "6_20", text = "adding to playlist", color = "#FFFFFF", timestampMs = 5700),
            // Loop 2
            DanmakuMessage(id = "6_21", text = "crying rn", color = "#FF69B4", timestampMs = 6100),
            DanmakuMessage(id = "6_22", text = "the story hits hard", color = "#FFD700", timestampMs = 6400),
            DanmakuMessage(id = "6_23", text = "who is cutting onions", color = "#FFFFFF", timestampMs = 6700),
            DanmakuMessage(id = "6_24", text = "bravo", color = "#00FF88", timestampMs = 6950),
            DanmakuMessage(id = "6_25", text = "standing ovation", color = "#FFD700", timestampMs = 7200),
            DanmakuMessage(id = "6_26", text = "tears in my eyes", color = "#FF6B6B", timestampMs = 7500),
            DanmakuMessage(id = "6_27", text = "cinema at its finest", color = "#00BFFF", timestampMs = 7800),
            DanmakuMessage(id = "6_28", text = "need therapy after this", color = "#FFFFFF", timestampMs = 8100),
            DanmakuMessage(id = "6_29", text = "beautiful destruction", color = "#FF69B4", timestampMs = 8400),
            DanmakuMessage(id = "6_30", text = "10/10", color = "#FFD700", timestampMs = 8700),
        ),
        "fake_007" to listOf(
            // Loop 0
            DanmakuMessage(id = "7_01", text = "480p bunny unlocked", color = "#FFFFFF", timestampMs = 100),
            DanmakuMessage(id = "7_02", text = "CRISPY", color = "#FFD700", timestampMs = 350),
            DanmakuMessage(id = "7_03", text = "the upgrade is real", color = "#00FF88", timestampMs = 600),
            DanmakuMessage(id = "7_04", text = "can see the fur now lol", color = "#FFFFFF", timestampMs = 900),
            DanmakuMessage(id = "7_05", text = "big bunny in HD", color = "#00BFFF", timestampMs = 1200),
            DanmakuMessage(id = "7_06", text = "quality content literally", color = "#FFD700", timestampMs = 1500),
            DanmakuMessage(id = "7_07", text = "pixels matter", color = "#FF69B4", timestampMs = 1800),
            DanmakuMessage(id = "7_08", text = "resolution gang", color = "#FF6B6B", timestampMs = 2100),
            DanmakuMessage(id = "7_09", text = "sharper than my life", color = "#FFFFFF", timestampMs = 2400),
            DanmakuMessage(id = "7_10", text = "4K waiting room", color = "#00FF88", timestampMs = 2700),
            // Loop 1
            DanmakuMessage(id = "7_11", text = "inject this into my veins", color = "#FF69B4", timestampMs = 3100),
            DanmakuMessage(id = "7_12", text = "premium content", color = "#FFD700", timestampMs = 3400),
            DanmakuMessage(id = "7_13", text = "so smooth", color = "#FFFFFF", timestampMs = 3700),
            DanmakuMessage(id = "7_14", text = "butter frames", color = "#00FF88", timestampMs = 3950),
            DanmakuMessage(id = "7_15", text = "the jump at the end tho", color = "#FF6B6B", timestampMs = 4200),
            DanmakuMessage(id = "7_16", text = "parkour bunny", color = "#00BFFF", timestampMs = 4500),
            DanmakuMessage(id = "7_17", text = "athletic specimen", color = "#FFD700", timestampMs = 4800),
            DanmakuMessage(id = "7_18", text = "olympian bunny", color = "#FFFFFF", timestampMs = 5100),
            DanmakuMessage(id = "7_19", text = "gold medal material", color = "#FF69B4", timestampMs = 5400),
            DanmakuMessage(id = "7_20", text = "hop king", color = "#00FF88", timestampMs = 5700),
            // Loop 2
            DanmakuMessage(id = "7_21", text = "every pixel matters", color = "#00BFFF", timestampMs = 6100),
            DanmakuMessage(id = "7_22", text = "this is why I have data", color = "#FFFFFF", timestampMs = 6400),
            DanmakuMessage(id = "7_23", text = "absolute W", color = "#FFD700", timestampMs = 6700),
            DanmakuMessage(id = "7_24", text = "top tier content", color = "#FF69B4", timestampMs = 6950),
            DanmakuMessage(id = "7_25", text = "dopamine hit", color = "#00FF88", timestampMs = 7200),
            DanmakuMessage(id = "7_26", text = "brain go brr", color = "#FF6B6B", timestampMs = 7500),
            DanmakuMessage(id = "7_27", text = "serotonin factory", color = "#FFD700", timestampMs = 7800),
            DanmakuMessage(id = "7_28", text = "endorphin rush", color = "#FFFFFF", timestampMs = 8100),
            DanmakuMessage(id = "7_29", text = "chemical happiness", color = "#00BFFF", timestampMs = 8400),
            DanmakuMessage(id = "7_30", text = "bunny pharmacy", color = "#FF69B4", timestampMs = 8700),
        ),
        "fake_008" to listOf(
            // Loop 0
            DanmakuMessage(id = "8_01", text = "HD jellyfish supremacy", color = "#00BFFF", timestampMs = 100),
            DanmakuMessage(id = "8_02", text = "the tentacles tho", color = "#FFFFFF", timestampMs = 350),
            DanmakuMessage(id = "8_03", text = "ok this one different", color = "#FFD700", timestampMs = 600),
            DanmakuMessage(id = "8_04", text = "ASMR for the eyes", color = "#FF69B4", timestampMs = 850),
            DanmakuMessage(id = "8_05", text = "floating through life", color = "#FFFFFF", timestampMs = 1100),
            DanmakuMessage(id = "8_06", text = "no thoughts just jelly", color = "#00FF88", timestampMs = 1400),
            DanmakuMessage(id = "8_07", text = "zen mode activated", color = "#FFD700", timestampMs = 1700),
            DanmakuMessage(id = "8_08", text = "stress leaving my body", color = "#FF6B6B", timestampMs = 2000),
            DanmakuMessage(id = "8_09", text = "cortisol dropping", color = "#00BFFF", timestampMs = 2300),
            DanmakuMessage(id = "8_10", text = "inner peace achieved", color = "#FFFFFF", timestampMs = 2600),
            // Loop 1
            DanmakuMessage(id = "8_11", text = "serotonin boost", color = "#FFD700", timestampMs = 3100),
            DanmakuMessage(id = "8_12", text = "aquarium vibes", color = "#00BFFF", timestampMs = 3400),
            DanmakuMessage(id = "8_13", text = "just keep swimming", color = "#FF6B6B", timestampMs = 3700),
            DanmakuMessage(id = "8_14", text = "nemo would be proud", color = "#FFFFFF", timestampMs = 3950),
            DanmakuMessage(id = "8_15", text = "underwater kino", color = "#FFD700", timestampMs = 4200),
            DanmakuMessage(id = "8_16", text = "deep blue energy", color = "#00FF88", timestampMs = 4500),
            DanmakuMessage(id = "8_17", text = "submarine POV", color = "#FF69B4", timestampMs = 4800),
            DanmakuMessage(id = "8_18", text = "depth charge of calm", color = "#00BFFF", timestampMs = 5100),
            DanmakuMessage(id = "8_19", text = "pressure? dont know her", color = "#FFFFFF", timestampMs = 5400),
            DanmakuMessage(id = "8_20", text = "abyssal chill", color = "#FF6B6B", timestampMs = 5700),
            // Loop 2
            DanmakuMessage(id = "8_21", text = "deep sea gang", color = "#00BFFF", timestampMs = 6100),
            DanmakuMessage(id = "8_22", text = "the glow on this one", color = "#FF69B4", timestampMs = 6400),
            DanmakuMessage(id = "8_23", text = "bioluminescence go brr", color = "#00FF88", timestampMs = 6700),
            DanmakuMessage(id = "8_24", text = "ocean is undefeated", color = "#FFFFFF", timestampMs = 6950),
            DanmakuMessage(id = "8_25", text = "save the seas fr", color = "#FFD700", timestampMs = 7200),
            DanmakuMessage(id = "8_26", text = "marine biology major rn", color = "#FF6B6B", timestampMs = 7500),
            DanmakuMessage(id = "8_27", text = "switching careers", color = "#00BFFF", timestampMs = 7800),
            DanmakuMessage(id = "8_28", text = "jelly researcher arc", color = "#FF69B4", timestampMs = 8100),
            DanmakuMessage(id = "8_29", text = "PhD in vibes", color = "#FFD700", timestampMs = 8400),
            DanmakuMessage(id = "8_30", text = "graduated with honors", color = "#00FF88", timestampMs = 8700),
        ),
        "fake_009" to listOf(
            // Loop 0
            DanmakuMessage(id = "9_01", text = "sintel 480p hits different", color = "#FFFFFF", timestampMs = 100),
            DanmakuMessage(id = "9_02", text = "the detail", color = "#FFD700", timestampMs = 400),
            DanmakuMessage(id = "9_03", text = "blender devs are cracked", color = "#00FF88", timestampMs = 700),
            DanmakuMessage(id = "9_04", text = "free software did THIS??", color = "#FFFFFF", timestampMs = 1000),
            DanmakuMessage(id = "9_05", text = "unreal", color = "#FF69B4", timestampMs = 1300),
            DanmakuMessage(id = "9_06", text = "texture work is nuts", color = "#00BFFF", timestampMs = 1600),
            DanmakuMessage(id = "9_07", text = "material nodes going crazy", color = "#FFD700", timestampMs = 1900),
            DanmakuMessage(id = "9_08", text = "subsurface scattering", color = "#FF6B6B", timestampMs = 2200),
            DanmakuMessage(id = "9_09", text = "skin shader on point", color = "#FFFFFF", timestampMs = 2500),
            DanmakuMessage(id = "9_10", text = "photorealistic almost", color = "#00FF88", timestampMs = 2800),
            // Loop 1
            DanmakuMessage(id = "9_11", text = "pixar could never", color = "#FFD700", timestampMs = 3100),
            DanmakuMessage(id = "9_12", text = "respect", color = "#00BFFF", timestampMs = 3400),
            DanmakuMessage(id = "9_13", text = "W W W W W", color = "#FF6B6B", timestampMs = 3700),
            DanmakuMessage(id = "9_14", text = "absolute cinema", color = "#FFFFFF", timestampMs = 3950),
            DanmakuMessage(id = "9_15", text = "the textures omg", color = "#FFD700", timestampMs = 4200),
            DanmakuMessage(id = "9_16", text = "cloth sim is wild", color = "#FF69B4", timestampMs = 4500),
            DanmakuMessage(id = "9_17", text = "wind dynamics", color = "#00FF88", timestampMs = 4800),
            DanmakuMessage(id = "9_18", text = "physically accurate", color = "#00BFFF", timestampMs = 5100),
            DanmakuMessage(id = "9_19", text = "simulation gang", color = "#FFFFFF", timestampMs = 5400),
            DanmakuMessage(id = "9_20", text = "physics engine W", color = "#FF6B6B", timestampMs = 5700),
            // Loop 2
            DanmakuMessage(id = "9_21", text = "3rd watch no regrets", color = "#00FF88", timestampMs = 6100),
            DanmakuMessage(id = "9_22", text = "open source greatness", color = "#FF69B4", timestampMs = 6400),
            DanmakuMessage(id = "9_23", text = "blender foundation W", color = "#FFFFFF", timestampMs = 6700),
            DanmakuMessage(id = "9_24", text = "this is why GPL exists", color = "#FFD700", timestampMs = 6950),
            DanmakuMessage(id = "9_25", text = "chef kiss", color = "#00BFFF", timestampMs = 7200),
            DanmakuMessage(id = "9_26", text = "community power", color = "#FF6B6B", timestampMs = 7500),
            DanmakuMessage(id = "9_27", text = "open source ftw", color = "#00FF88", timestampMs = 7800),
            DanmakuMessage(id = "9_28", text = "contributors are heroes", color = "#FFFFFF", timestampMs = 8100),
            DanmakuMessage(id = "9_29", text = "donate to blender", color = "#FFD700", timestampMs = 8400),
            DanmakuMessage(id = "9_30", text = "legend status", color = "#FF69B4", timestampMs = 8700),
        ),
        "fake_010" to listOf(
            // Loop 0
            DanmakuMessage(id = "10_01", text = "bunny in 2MB quality", color = "#FFFFFF", timestampMs = 100),
            DanmakuMessage(id = "10_02", text = "we eating good", color = "#FFD700", timestampMs = 350),
            DanmakuMessage(id = "10_03", text = "the budget version", color = "#FF69B4", timestampMs = 600),
            DanmakuMessage(id = "10_04", text = "still slaps", color = "#FFFFFF", timestampMs = 900),
            DanmakuMessage(id = "10_05", text = "compression who??", color = "#00FF88", timestampMs = 1200),
            DanmakuMessage(id = "10_06", text = "bitrate is a lifestyle", color = "#00BFFF", timestampMs = 1500),
            DanmakuMessage(id = "10_07", text = "codec wars", color = "#FFD700", timestampMs = 1800),
            DanmakuMessage(id = "10_08", text = "h264 supremacy", color = "#FF6B6B", timestampMs = 2100),
            DanmakuMessage(id = "10_09", text = "encoding gang", color = "#FFFFFF", timestampMs = 2400),
            DanmakuMessage(id = "10_10", text = "ffmpeg entered the chat", color = "#FF69B4", timestampMs = 2700),
            // Loop 1
            DanmakuMessage(id = "10_11", text = "thicc bunny arc", color = "#00BFFF", timestampMs = 3100),
            DanmakuMessage(id = "10_12", text = "lmaooo", color = "#FFD700", timestampMs = 3400),
            DanmakuMessage(id = "10_13", text = "subscribed", color = "#FFFFFF", timestampMs = 3700),
            DanmakuMessage(id = "10_14", text = "the homie is back", color = "#FF6B6B", timestampMs = 3950),
            DanmakuMessage(id = "10_15", text = "round 4 of bunny", color = "#00FF88", timestampMs = 4200),
            DanmakuMessage(id = "10_16", text = "dedication", color = "#FFD700", timestampMs = 4500),
            DanmakuMessage(id = "10_17", text = "loyalty badge earned", color = "#FF69B4", timestampMs = 4800),
            DanmakuMessage(id = "10_18", text = "bunny stan account", color = "#00BFFF", timestampMs = 5100),
            DanmakuMessage(id = "10_19", text = "official fan club", color = "#FFFFFF", timestampMs = 5400),
            DanmakuMessage(id = "10_20", text = "president of the fandom", color = "#FF6B6B", timestampMs = 5700),
            // Loop 2
            DanmakuMessage(id = "10_21", text = "dedicated to the bunny", color = "#FF69B4", timestampMs = 6100),
            DanmakuMessage(id = "10_22", text = "loyalty", color = "#FFD700", timestampMs = 6400),
            DanmakuMessage(id = "10_23", text = "bunny cinematic universe", color = "#FFFFFF", timestampMs = 6700),
            DanmakuMessage(id = "10_24", text = "phase 4 confirmed", color = "#00BFFF", timestampMs = 6950),
            DanmakuMessage(id = "10_25", text = "post credits scene when", color = "#FF6B6B", timestampMs = 7200),
            DanmakuMessage(id = "10_26", text = "end game bunny", color = "#00FF88", timestampMs = 7500),
            DanmakuMessage(id = "10_27", text = "infinity saga", color = "#FFD700", timestampMs = 7800),
            DanmakuMessage(id = "10_28", text = "snap and half the carrots gone", color = "#FFFFFF", timestampMs = 8100),
            DanmakuMessage(id = "10_29", text = "inevitable", color = "#FF69B4", timestampMs = 8400),
            DanmakuMessage(id = "10_30", text = "perfectly balanced", color = "#00BFFF", timestampMs = 8700),
        ),
        "fake_011" to listOf(
            // Loop 0
            DanmakuMessage(id = "11_01", text = "more jelly content pls", color = "#00BFFF", timestampMs = 100),
            DanmakuMessage(id = "11_02", text = "the colors omg", color = "#FF69B4", timestampMs = 350),
            DanmakuMessage(id = "11_03", text = "ocean documentary vibes", color = "#FFFFFF", timestampMs = 600),
            DanmakuMessage(id = "11_04", text = "David Attenborough type beat", color = "#FFD700", timestampMs = 900),
            DanmakuMessage(id = "11_05", text = "nature is the GOAT", color = "#00FF88", timestampMs = 1200),
            DanmakuMessage(id = "11_06", text = "sending this to everyone", color = "#FFFFFF", timestampMs = 1500),
            DanmakuMessage(id = "11_07", text = "group chat gonna love this", color = "#FF6B6B", timestampMs = 1800),
            DanmakuMessage(id = "11_08", text = "screenshot and send", color = "#FFD700", timestampMs = 2100),
            DanmakuMessage(id = "11_09", text = "viral material", color = "#00BFFF", timestampMs = 2400),
            DanmakuMessage(id = "11_10", text = "trending soon", color = "#FF69B4", timestampMs = 2700),
            // Loop 1
            DanmakuMessage(id = "11_11", text = "beautiful", color = "#FFD700", timestampMs = 3100),
            DanmakuMessage(id = "11_12", text = "protect the oceans", color = "#00BFFF", timestampMs = 3400),
            DanmakuMessage(id = "11_13", text = "crying rn", color = "#FF6B6B", timestampMs = 3700),
            DanmakuMessage(id = "11_14", text = "we dont deserve jelly", color = "#FFFFFF", timestampMs = 3950),
            DanmakuMessage(id = "11_15", text = "underwater GOAT", color = "#FFD700", timestampMs = 4200),
            DanmakuMessage(id = "11_16", text = "blue planet energy", color = "#00FF88", timestampMs = 4500),
            DanmakuMessage(id = "11_17", text = "BBC documentary when", color = "#00BFFF", timestampMs = 4800),
            DanmakuMessage(id = "11_18", text = "narrate this someone", color = "#FFFFFF", timestampMs = 5100),
            DanmakuMessage(id = "11_19", text = "morgan freeman voice", color = "#FF69B4", timestampMs = 5400),
            DanmakuMessage(id = "11_20", text = "epic narrator needed", color = "#FFD700", timestampMs = 5700),
            // Loop 2
            DanmakuMessage(id = "11_21", text = "final loop appreciation", color = "#FF69B4", timestampMs = 6100),
            DanmakuMessage(id = "11_22", text = "brb setting as wallpaper", color = "#00FF88", timestampMs = 6400),
            DanmakuMessage(id = "11_23", text = "screenshotted", color = "#FFFFFF", timestampMs = 6700),
            DanmakuMessage(id = "11_24", text = "museum quality", color = "#FFD700", timestampMs = 6950),
            DanmakuMessage(id = "11_25", text = "immaculate vibes", color = "#00BFFF", timestampMs = 7200),
            DanmakuMessage(id = "11_26", text = "framing this", color = "#FF6B6B", timestampMs = 7500),
            DanmakuMessage(id = "11_27", text = "NFT this jk", color = "#FFFFFF", timestampMs = 7800),
            DanmakuMessage(id = "11_28", text = "priceless", color = "#FF69B4", timestampMs = 8100),
            DanmakuMessage(id = "11_29", text = "gallery worthy", color = "#FFD700", timestampMs = 8400),
            DanmakuMessage(id = "11_30", text = "Louvre is calling", color = "#00FF88", timestampMs = 8700),
        ),
        "fake_012" to listOf(
            // Loop 0
            DanmakuMessage(id = "12_01", text = "the finale", color = "#FFFFFF", timestampMs = 100),
            DanmakuMessage(id = "12_02", text = "saved the best for last", color = "#FFD700", timestampMs = 350),
            DanmakuMessage(id = "12_03", text = "sintel in full glory", color = "#FF6B6B", timestampMs = 600),
            DanmakuMessage(id = "12_04", text = "emotional damage", color = "#FFFFFF", timestampMs = 900),
            DanmakuMessage(id = "12_05", text = "the story is so good", color = "#FF69B4", timestampMs = 1200),
            DanmakuMessage(id = "12_06", text = "who is cutting onions", color = "#00BFFF", timestampMs = 1500),
            DanmakuMessage(id = "12_07", text = "backstory when", color = "#FFD700", timestampMs = 1800),
            DanmakuMessage(id = "12_08", text = "lore is deep", color = "#00FF88", timestampMs = 2100),
            DanmakuMessage(id = "12_09", text = "worldbuilding insane", color = "#FF6B6B", timestampMs = 2400),
            DanmakuMessage(id = "12_10", text = "tolkien energy", color = "#FFFFFF", timestampMs = 2700),
            // Loop 1
            DanmakuMessage(id = "12_11", text = "why am I tearing up", color = "#FFFFFF", timestampMs = 3100),
            DanmakuMessage(id = "12_12", text = "open source cinema peak", color = "#00FF88", timestampMs = 3400),
            DanmakuMessage(id = "12_13", text = "standing ovation", color = "#FFD700", timestampMs = 3700),
            DanmakuMessage(id = "12_14", text = "bravo", color = "#FFFFFF", timestampMs = 3950),
            DanmakuMessage(id = "12_15", text = "need a full movie NOW", color = "#FF6B6B", timestampMs = 4200),
            DanmakuMessage(id = "12_16", text = "kickstarter link pls", color = "#00BFFF", timestampMs = 4500),
            DanmakuMessage(id = "12_17", text = "take my money", color = "#FFD700", timestampMs = 4800),
            DanmakuMessage(id = "12_18", text = "all my tokens", color = "#FF69B4", timestampMs = 5100),
            DanmakuMessage(id = "12_19", text = "shut up and take my wallet", color = "#FFFFFF", timestampMs = 5400),
            DanmakuMessage(id = "12_20", text = "funded in 10 minutes", color = "#00FF88", timestampMs = 5700),
            // Loop 2
            DanmakuMessage(id = "12_21", text = "petition for sequel", color = "#FF69B4", timestampMs = 6100),
            DanmakuMessage(id = "12_22", text = "fund it on kickstarter", color = "#FFD700", timestampMs = 6400),
            DanmakuMessage(id = "12_23", text = "id pay for this", color = "#00BFFF", timestampMs = 6700),
            DanmakuMessage(id = "12_24", text = "greatest of all time", color = "#FFFFFF", timestampMs = 6950),
            DanmakuMessage(id = "12_25", text = "perfect ending", color = "#00FF88", timestampMs = 7200),
            DanmakuMessage(id = "12_26", text = "10/10 no notes", color = "#FFD700", timestampMs = 7500),
            DanmakuMessage(id = "12_27", text = "oscar worthy", color = "#FF6B6B", timestampMs = 7800),
            DanmakuMessage(id = "12_28", text = "academy award please", color = "#FFFFFF", timestampMs = 8100),
            DanmakuMessage(id = "12_29", text = "golden globe incoming", color = "#FF69B4", timestampMs = 8400),
            DanmakuMessage(id = "12_30", text = "GOAT forever", color = "#FFD700", timestampMs = 8700),
        ),
    )
}
